### ISSUE TITLE
Inconsistent `manifold_tensor.proj_`

### ISSUE THREAD

**Issue by ferrine** [geoopt/geoopt#72]
Now `proj_` in Manifold tensor does not raise a RuntimeError, but it should to be consistent with torch API. Similar as below behaviour is expected.
```python
t = torch.rand(10).requires_grad_()
t.fill_(1)
Traceback (most recent call last):
  File "/Users/ferres/dev/cvx_ha/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-a34fdbf25f1e>", line 1, in <module>
```

**Comment by ferrine** [comment]
Closed via #77
